version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 sync --delete . "s3://codepipeline-ca-central-1-751716897608"
 post_build:
   commands:
     - echo "post_build step"